/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.medico;

import Animacion.Fade;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import sistema.alertas.Hecho;
import sistema.database.FamiliaresDTO;
import sistema.util.CalcularEdad;
import sistema.util.CustomUI;
/**
 *
 * @author Administrador
 */
public class AñadirFamiliar extends javax.swing.JDialog {

    /**
     * Creates new form AñadirFamiliar
     */
    int ID_Paciente;
    int x, y;

    public AñadirFamiliar(JDialog parent, boolean modal, int ID_Paciente) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        //this.parent = parent;
        this.setLocationRelativeTo(parent);
        setOpacity(0f);
        this.ID_Paciente = ID_Paciente;
        Fade.JDialogFadeIn(0f, 1f, 0.2f, 50, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("static-access")
    private void initComponents() {

        panelDatosFamiliares = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        etiquetaDatosDelFamiliar = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        etiquetaNombreFamiliar = new javax.swing.JLabel();
        entradaNombreFamiliar = new javax.swing.JTextField();
        etiquetaApellidoFamiliar = new javax.swing.JLabel();
        entradaApellidoFamiliar = new javax.swing.JTextField();
        etiquetaCedulaFamiliar = new javax.swing.JLabel();
        entradaCedulaFamiliar = new javax.swing.JTextField();
        etiquetaFechaNacimientoFamiliar = new javax.swing.JLabel();
        entradaFechaNacimientoFamiliar = new javax.swing.JTextField();
        FechaNacimientoFamiliar = new com.toedter.calendar.JDateChooser();
        etiquetaParentescoFamiliar = new javax.swing.JLabel();
        listParentescoFamiliar = new javax.swing.JComboBox<>();
        etiquetaGeneroFamiliar = new javax.swing.JLabel();
        listGeneroFamiliar = new javax.swing.JComboBox<>();
        btnAgregarFamiliar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelDatosFamiliares.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosFamiliares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelDatosFamiliaresFocusGained(evt);
            }
        });
        panelDatosFamiliares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelDatosFamiliaresKeyPressed(evt);
            }
        });
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorderE = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorderE .setShowRightShadow(true);
        dropShadowBorderE .setShowLeftShadow(true);
        dropShadowBorderE .setShowTopShadow(true);
        dropShadowBorderE .setShowBottomShadow(true);

        panelDatosFamiliares.setBorder(dropShadowBorderE);
        panelDatosFamiliares.setLayout(null);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono cerrar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono cerrar pressed.png"))); // NOI18N
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono cerrar rollover.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelDatosFamiliares.add(btnCerrar);
        btnCerrar.setBounds(724, 10, 36, 36);

        etiquetaDatosDelFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        etiquetaDatosDelFamiliar.setForeground(new java.awt.Color(0, 0, 153));
        etiquetaDatosDelFamiliar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDatosDelFamiliar.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent evt) {
                x = evt.getX();
                y = evt.getY();
            }
        });
        etiquetaDatosDelFamiliar.addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent evt) {
                Point point = MouseInfo.getPointerInfo().getLocation();
                setLocation(point.x - x, point.y - y);
            }
        });
        etiquetaDatosDelFamiliar.setText("Datos del Familiar");
        panelDatosFamiliares.add(etiquetaDatosDelFamiliar);
        etiquetaDatosDelFamiliar.setBounds(0, 2, 770, 60);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/line.png"))); // NOI18N
        panelDatosFamiliares.add(jLabel44);
        jLabel44.setBounds(290, 30, 180, 20);

        etiquetaNombreFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaNombreFamiliar.setText("Nombres");
        etiquetaNombreFamiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etiquetaNombreFamiliar.setFocusable(false);
        panelDatosFamiliares.add(etiquetaNombreFamiliar);
        etiquetaNombreFamiliar.setBounds(60, 94, 100, 20);

        entradaNombreFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaNombreFamiliar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(180, 180, 180)));
        entradaNombreFamiliar.addFocusListener(new EscucharBotones().focus(etiquetaNombreFamiliar,0,0,153));
        entradaNombreFamiliar.addKeyListener(new EscucharBotones.AccionesTxt("texto"));
        /*
        entradaNombreFamiliar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaNombreFamiliarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaNombreFamiliarFocusLost(evt);
            }
        });
        entradaNombreFamiliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaNombreFamiliarMouseClicked(evt);
            }
        });
        entradaNombreFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreFamiliarActionPerformed(evt);
            }
        });
        */
        panelDatosFamiliares.add(entradaNombreFamiliar);
        entradaNombreFamiliar.setBounds(60, 100, 220, 24);

        etiquetaApellidoFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaApellidoFamiliar.setText("Apellidos");
        etiquetaApellidoFamiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etiquetaApellidoFamiliar.setFocusable(false);
        panelDatosFamiliares.add(etiquetaApellidoFamiliar);
        etiquetaApellidoFamiliar.setBounds(310, 94, 100, 20);

        entradaApellidoFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaApellidoFamiliar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(180, 180, 180)));
        entradaApellidoFamiliar.addFocusListener(new EscucharBotones().focus(etiquetaApellidoFamiliar,0,0,153));
        entradaApellidoFamiliar.addKeyListener(new EscucharBotones.AccionesTxt("texto"));
        /*
        entradaApellidoFamiliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaApellidoFamiliarMouseClicked(evt);
            }
        });
        */
        panelDatosFamiliares.add(entradaApellidoFamiliar);
        entradaApellidoFamiliar.setBounds(310, 100, 220, 24);

        etiquetaCedulaFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaCedulaFamiliar.setText("Cedula");
        etiquetaCedulaFamiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etiquetaCedulaFamiliar.setFocusable(false);
        panelDatosFamiliares.add(etiquetaCedulaFamiliar);
        etiquetaCedulaFamiliar.setBounds(560, 94, 100, 20);

        entradaCedulaFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaCedulaFamiliar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
       
        entradaCedulaFamiliar.addFocusListener(new EscucharBotones().focus(etiquetaCedulaFamiliar,0,0,153));
        entradaCedulaFamiliar.addKeyListener(new EscucharBotones.AccionesTxt("numerico"));
        panelDatosFamiliares.add(entradaCedulaFamiliar);
        entradaCedulaFamiliar.setBounds(560, 100, 150, 24);

        etiquetaFechaNacimientoFamiliar.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaFechaNacimientoFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaFechaNacimientoFamiliar.setText("Fecha de nacimiento");
        etiquetaFechaNacimientoFamiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etiquetaFechaNacimientoFamiliar.setFocusable(false);
        panelDatosFamiliares.add(etiquetaFechaNacimientoFamiliar);
        etiquetaFechaNacimientoFamiliar.setBounds(60, 194, 150, 20);

        entradaFechaNacimientoFamiliar.setEditable(false);
        entradaFechaNacimientoFamiliar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        panelDatosFamiliares.add(entradaFechaNacimientoFamiliar);
        entradaFechaNacimientoFamiliar.setBounds(60, 200, 180, 24);

        FechaNacimientoFamiliar.setBackground(new java.awt.Color(255, 255, 255));
        FechaNacimientoFamiliar.setOpaque(false);
       
        FechaNacimientoFamiliar.addPropertyChangeListener(new principal.date(entradaFechaNacimientoFamiliar,FechaNacimientoFamiliar,etiquetaFechaNacimientoFamiliar));
        panelDatosFamiliares.add(FechaNacimientoFamiliar);
        FechaNacimientoFamiliar.setBounds(60, 200, 220, 24);

        etiquetaParentescoFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        etiquetaParentescoFamiliar.setForeground(new java.awt.Color(153, 153, 153));
        etiquetaParentescoFamiliar.setText("Relacion de parentesco con el paciente");
        panelDatosFamiliares.add(etiquetaParentescoFamiliar);
        etiquetaParentescoFamiliar.setBounds(310, 180, 200, 20);

        listParentescoFamiliar.setEditable(true);
        listParentescoFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        listParentescoFamiliar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PARENTESCO", "MADRE", "PADRE", "ABUELO" }));
        listParentescoFamiliar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        listParentescoFamiliar.setUI(CustomUI.createUI(rootPane));
        panelDatosFamiliares.add(listParentescoFamiliar);
        listParentescoFamiliar.setBounds(310, 200, 220, 24);

        etiquetaGeneroFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        etiquetaGeneroFamiliar.setForeground(new java.awt.Color(153, 153, 153));
        etiquetaGeneroFamiliar.setText("Genero del familiar");
        panelDatosFamiliares.add(etiquetaGeneroFamiliar);
        etiquetaGeneroFamiliar.setBounds(560, 180, 100, 20);

        listGeneroFamiliar.setEditable(true);
        listGeneroFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        listGeneroFamiliar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERO", "FEMENINO", "MASCULINO" }));
        listGeneroFamiliar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        listGeneroFamiliar.setUI(CustomUI.createUI(rootPane));
        panelDatosFamiliares.add(listGeneroFamiliar);
        listGeneroFamiliar.setBounds(560, 200, 150, 24);

        btnAgregarFamiliar.setBackground(new java.awt.Color(191, 247, 0));
        btnAgregarFamiliar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnAgregarFamiliar.setText("Agregar ");
        btnAgregarFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFamiliarActionPerformed(evt);
            }
        });
        panelDatosFamiliares.add(btnAgregarFamiliar);
        btnAgregarFamiliar.setBounds(90, 280, 200, 28);

        btnCancelar.setBackground(new java.awt.Color(191, 247, 0));
        btnCancelar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelDatosFamiliares.add(btnCancelar);
        btnCancelar.setBounds(470, 280, 200, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosFamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosFamiliares, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFamiliarActionPerformed
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) listParentescoFamiliar.getModel();
        DefaultComboBoxModel<String> modelo1 = (DefaultComboBoxModel<String>) listGeneroFamiliar.getModel();
        int result = 0;
        if (entradaNombreFamiliar.getText().equals("")
                || entradaApellidoFamiliar.getText().equals("")
                || entradaCedulaFamiliar.getText().equals("")
                || entradaFechaNacimientoFamiliar.getText().equals("")
                || modelo.getSelectedItem().equals("PARENTESCO")
                || modelo1.getSelectedItem().equals("GENERO")) {
            new sistema.alertas.Error(this, true, "\nTODOS LOS CAMPOS SON REQUERIDOS").setVisible(true);
        } else {
            Collection<FamiliaresDTO> collFamiliares = Facade.ConsultarFamiliaresEspecificos("ID_Paciente", ID_Paciente);
            for (FamiliaresDTO dto : collFamiliares) {
                if (dto.getCedula() == Integer.parseInt(entradaCedulaFamiliar.getText())) {
                    new sistema.alertas.Error(this, true, "YA EXISTE UN FAMILIAR CON ESE NUMERO DE CEDULA").setVisible(true);
                    result = 1;
                    break;
                } else if (dto.getParentesco().equals("MADRE") && modelo.getSelectedItem().toString().equals("MADRE")
                        || dto.getParentesco().equals("PADRE") && modelo.getSelectedItem().toString().equals("PADRE")) {
                    new sistema.alertas.Error(this, true, "YA EXISTE UN FAMILIAR CON ESA RELACION DE PARENTESCO").setVisible(true);
                    result = 1;
                    break;
                }
            }
            if (result == 0) {
                FamiliaresDTO familiar = new FamiliaresDTO();
                familiar.setID_Paciente(ID_Paciente);
                familiar.setNombre(entradaNombreFamiliar.getText().toUpperCase());
                familiar.setApellido(entradaApellidoFamiliar.getText().toUpperCase());
                familiar.setCedula(Integer.parseInt(entradaCedulaFamiliar.getText()));
                familiar.setFechaDeNacimiento(entradaFechaNacimientoFamiliar.getText().toUpperCase());
                familiar.setEdad(CalcularEdad.convertir(entradaFechaNacimientoFamiliar.getText()));
                familiar.setParentesco(modelo.getSelectedItem().toString());
                familiar.setGenero(modelo1.getSelectedItem().toString());
                Facade.AñadirFamiliares(familiar);
                new Hecho(this, true).setVisible(true);
                Fade.JDialogFadeOut(1, 0, 0.1f, 50, this, Fade.DISPOSE);
                VerDatosPaciente.llenarTablaFamiliares("ID_Paciente", ID_Paciente);
            }
        }
    }//GEN-LAST:event_btnAgregarFamiliarActionPerformed

    private void panelDatosFamiliaresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelDatosFamiliaresFocusGained
        //etiquetaProgreso.setIcon(new ImageIcon(getClass().getResource("/img/icono progreso1.png")));
    }//GEN-LAST:event_panelDatosFamiliaresFocusGained

    private void panelDatosFamiliaresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelDatosFamiliaresKeyPressed

    }//GEN-LAST:event_panelDatosFamiliaresKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Fade.JDialogFadeOut(1, 0, 0.1f, 50, this, Fade.DISPOSE);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Fade.JDialogFadeOut(1, 0, 0.1f, 50, this, Fade.DISPOSE);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AñadirFamiliar dialog = new AñadirFamiliar(new JDialog(), true, 5423);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaNacimientoFamiliar;
    private javax.swing.JButton btnAgregarFamiliar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JTextField entradaApellidoFamiliar;
    private javax.swing.JTextField entradaCedulaFamiliar;
    private javax.swing.JTextField entradaFechaNacimientoFamiliar;
    private javax.swing.JTextField entradaNombreFamiliar;
    private javax.swing.JLabel etiquetaApellidoFamiliar;
    private javax.swing.JLabel etiquetaCedulaFamiliar;
    private javax.swing.JLabel etiquetaDatosDelFamiliar;
    private javax.swing.JLabel etiquetaFechaNacimientoFamiliar;
    private javax.swing.JLabel etiquetaGeneroFamiliar;
    private javax.swing.JLabel etiquetaNombreFamiliar;
    private javax.swing.JLabel etiquetaParentescoFamiliar;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JComboBox<String> listGeneroFamiliar;
    private javax.swing.JComboBox<String> listParentescoFamiliar;
    private javax.swing.JPanel panelDatosFamiliares;
    // End of variables declaration//GEN-END:variables
}
