/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.medico;

import Animacion.Fade;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import sistema.alertas.Hecho;
import sistema.database.DatosMedicosPacienteDTO;
import sistema.util.CustomUI;

/**
 *
 * @author Administrador
 */
public class AñadirDatoMedico extends javax.swing.JDialog {

    /**
     * Creates new form AñadirDatoMedico
     */
    JDialog dialogo;
    int ID_Paciente;
    int x, y;

    public AñadirDatoMedico(JFrame parent, boolean modal, int ID_Paciente) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        entrada.setVisible(false);
        etiquetaNombre.setVisible(false);
        list1.setVisible(false);
        etiqueta1.setVisible(false);
        this.setLocationRelativeTo(parent);
        setOpacity(0f);
        this.ID_Paciente = ID_Paciente;
        dialogo = this;
        Fade.JDialogFadeIn(0f, 1f, 0.2f, 50, this);
    }

    public AñadirDatoMedico(JDialog parent, boolean modal, int ID_Paciente) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        entrada.setVisible(false);
        etiquetaNombre.setVisible(false);
        list1.setVisible(false);
        etiqueta1.setVisible(false);
        this.setLocationRelativeTo(parent);
        setOpacity(0f);
        dialogo = this;
        this.ID_Paciente = ID_Paciente;
        Fade.JDialogFadeIn(0f, 1f, 0.2f, 50, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("static-access")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        list = new javax.swing.JComboBox<>();
        etiquetaNombre = new javax.swing.JLabel();
        entrada = new javax.swing.JTextField();
        btbCancelar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        etiquetaAñadir = new javax.swing.JLabel();
        etiqueta = new javax.swing.JLabel();
        list1 = new javax.swing.JComboBox<>();
        etiqueta1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        list.setBackground(new java.awt.Color(0, 0, 0));
        list.setEditable(true);
        list.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        list.setForeground(new java.awt.Color(255, 255, 255));
        list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE DATO MEDICO", "ALERGIAS", "ENFERMEDADES CRONICAS", "CIRUGIAS" }));
        list.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        list.setUI(CustomUI.createUI(rootPane));
        list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listItemStateChanged(evt);
            }
        });
        jPanel1.add(list);
        list.setBounds(40, 130, 470, 25);

        etiquetaNombre.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaNombre.setText("Nombre de la Alergia");
        etiquetaNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaNombre);
        etiquetaNombre.setBounds(280, 124, 240, 20);

        entrada.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entrada.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entrada.addFocusListener(new EscucharBotones().focus(etiquetaNombre,0,0,153));
        entrada.addActionListener(new acciones());
        entrada.addKeyListener(new EscucharBotones.AccionesTxt("texto"));
        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });
        jPanel1.add(entrada);
        entrada.setBounds(280, 130, 240, 24);

        btbCancelar.setBackground(new java.awt.Color(0, 0, 153));
        btbCancelar.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        btbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btbCancelar.setText("Cancelar");
        btbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btbCancelar);
        btbCancelar.setBounds(340, 200, 160, 29);

        btnAñadir.setBackground(new java.awt.Color(0, 0, 153));
        btnAñadir.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new acciones());
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir);
        btnAñadir.setBounds(40, 200, 160, 29);

        etiquetaAñadir.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        etiquetaAñadir.setForeground(new java.awt.Color(0, 0, 102));
        etiquetaAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAñadir.setText("Añadir dato Medico");
        etiquetaAñadir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiquetaAñadir.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent evt) {
                x = evt.getX();
                y = evt.getY();
            }
        });
        etiquetaAñadir.addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent evt) {
                Point point = MouseInfo.getPointerInfo().getLocation();
                setLocation(point.x - x, point.y - y);
            }
        });
        jPanel1.add(etiquetaAñadir);
        etiquetaAñadir.setBounds(0, -1, 540, 50);

        etiqueta.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        etiqueta.setForeground(new java.awt.Color(153, 153, 153));
        etiqueta.setText("Seleccione el tipo de dato medico");
        jPanel1.add(etiqueta);
        etiqueta.setBounds(40, 100, 220, 13);

        list1.setBackground(new java.awt.Color(0, 0, 0));
        list1.setEditable(true);
        list1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        list1.setForeground(new java.awt.Color(255, 255, 255));
        list1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE DATO MEDICO", "ALERGIAS", "ENFERMEDADES CRONICAS", "CIRUGIAS" }));
        list1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        list1.setUI(CustomUI.createUI(rootPane));
        list1.getEditor().getEditorComponent().addKeyListener(new acciones());
        list1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list1ItemStateChanged(evt);
            }
        });
        jPanel1.add(list1);
        list1.setBounds(280, 130, 220, 25);

        etiqueta1.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        etiqueta1.setForeground(new java.awt.Color(153, 153, 153));
        etiqueta1.setText("Seleccione el tipo de dato medico");
        jPanel1.add(etiqueta1);
        etiqueta1.setBounds(280, 100, 220, 13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaActionPerformed

    private void btbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarActionPerformed
        // this.dispose();
        Fade.JDialogFadeOut(1f, 0f, 0.2f, 50, this, Fade.DISPOSE);
    }//GEN-LAST:event_btbCancelarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed

    }//GEN-LAST:event_btnAñadirActionPerformed

    class acciones implements ActionListener, KeyListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            añadir();
        }

        @Override
        public void keyTyped(KeyEvent ke) {
        }

        @Override
        public void keyPressed(KeyEvent ke) {
            if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
                añadir();
            }
        }

        @Override
        public void keyReleased(KeyEvent ke) {
        }
    }

    private void añadir() {
        if (list.getSelectedIndex() == 0) {
            new sistema.alertas.Error(dialogo, true, "DEBE SELECCIONAR EL TIPO DE DATO MEDICO A INTRODUCIR").setVisible(true);
        } else {
            if (list.getSelectedIndex() == 1 && entrada.getText().equals("")
                    || list.getSelectedIndex() > 1 && list1.getSelectedIndex() < 1) {
                new sistema.alertas.Error(dialogo, true, "EL CAMPO NO PUEDE ESTAR VACIO").setVisible(true);
            } else {
                String msj;
                Collection<DatosMedicosPacienteDTO> coll;
                int result = 0;
                DatosMedicosPacienteDTO datos = new DatosMedicosPacienteDTO();
                switch (list.getSelectedIndex()) {
                    case 1:
                        datos.setTipo("Alergias");
                        datos.setNombre(entrada.getText().toUpperCase());
                        msj = "ALERGIA";
                        coll = Facade.ConsultarDatosMedicos("Alergias", ID_Paciente, entrada.getText().toUpperCase());
                        break;
                    case 2:
                        datos.setTipo("Enfermedades Cronicas");
                        datos.setNombre(list1.getSelectedItem().toString());
                        msj = "ENFERMEDAD CRONICA";
                        coll = Facade.ConsultarDatosMedicos("Enfermedades Cronicas", ID_Paciente, list1.getSelectedItem().toString());
                        break;
                    default:
                        datos.setTipo("Cirugias");
                        datos.setNombre(list1.getSelectedItem().toString());
                        msj = "CIRUGIA";
                        coll = Facade.ConsultarDatosMedicos("Cirugias", ID_Paciente, list1.getSelectedItem().toString());
                        break;
                }
                for (DatosMedicosPacienteDTO dto : coll) {
                    result = dto.getFilasAfectadas();
                }
                if (result > 0) {
                    new sistema.alertas.Error(dialogo, true, "YA EXISTE UNA " + msj + " CON ESE NOMBRE").setVisible(true);
                } else {
                    datos.setID_Paciente(ID_Paciente);
                    Facade.AñadirDatosMedicosPaciente(datos);
                    new Hecho(dialogo, true).setVisible(true);
                    VerDatosPaciente.llenarTablaPacientes("ID_Paciente", ID_Paciente);
                    Fade.JDialogFadeOut(1f, 0f, 0.2f, 50, this, Fade.DISPOSE);
                }
            }
        }
    }

    private void listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listItemStateChanged
        switch (list.getSelectedIndex()) {
            case 0:
                etiqueta1.setVisible(false);
                list1.setVisible(false);
                etiquetaNombre.setVisible(false);
                entrada.setVisible(false);
                list.setBounds(40, 130, 470, 25);
                break;
            case 1:
                etiquetaNombre.setBounds(280, 124, 220, 25);
                entrada.setBounds(280, 130, 240, 25);
                etiquetaNombre.setVisible(true);
                entrada.setVisible(true);
                list1.setVisible(false);
                etiqueta1.setVisible(false);
                list.setBounds(40, 130, 220, 25);
                break;
            case 2:
            case 3:
                DefaultComboBoxModel<String> modelo;
                modelo = (DefaultComboBoxModel<String>) list1.getModel();
                modelo.removeAllElements();
                etiqueta1.setBounds(280, 100, 220, etiqueta1.getHeight());
                list1.setBounds(280, 130, 240, 25);
                etiquetaNombre.setVisible(false);
                entrada.setVisible(false);
                list1.setVisible(true);
                etiqueta1.setVisible(true);
                list.setBounds(40, 130, 220, 25);
                if (list.getSelectedIndex() == 2) {
                    etiqueta1.setText("Selecione la enfermedad cronica");
                    modelo.addElement("SELECCIONE");
                    modelo.addElement("ASMA");
                    modelo.addElement("HIPERTENSION");
                    modelo.addElement("DIABETES");
                    modelo.addElement("AZUCAR EN LA SANGRE");
                } else {
                    etiqueta1.setText("Selecione la cirugia");
                    modelo.addElement("SELECCIONE");
                    modelo.addElement("LOT");
                    modelo.addElement("YUGULAR");
                    modelo.addElement("RIÑON");
                    modelo.addElement("PULMON");
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_listItemStateChanged

    private void list1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirDatoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirDatoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirDatoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirDatoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AñadirDatoMedico dialog = new AñadirDatoMedico(new javax.swing.JFrame(), true, 12);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancelar;
    public javax.swing.JButton btnAñadir;
    public javax.swing.JTextField entrada;
    public javax.swing.JLabel etiqueta;
    public javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiquetaAñadir;
    public javax.swing.JLabel etiquetaNombre;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> list;
    public javax.swing.JComboBox<String> list1;
    // End of variables declaration//GEN-END:variables
}
