/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.medico;

import Animacion.Fade;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.ArrayList;
import javax.swing.JDialog;
import sistema.alertas.Hecho;
import sistema.database.UsuariosDTO;

/**
 *
 * @author Administrador
 */
public class CambiarPassword extends javax.swing.JDialog {

    /**
     * Creates new form CambiarPassword
     */
    int cedula;
    int x, y;

    public CambiarPassword(JDialog parent, boolean modal, int cedula) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        this.cedula = cedula;
        this.setLocationRelativeTo(parent);
        setOpacity(0f);
        Fade.JDialogFadeIn(0f, 1f, 0.2f, 50, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("static-access")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaContraseñaActual = new javax.swing.JLabel();
        btbCancelar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        etiquetaAñadir = new javax.swing.JLabel();
        etiquetaContraseñaNueva = new javax.swing.JLabel();
        etiquetaConfirmarContraseña = new javax.swing.JLabel();
        entradaContraseñaActual = new javax.swing.JPasswordField();
        entradaContraseñaNueva = new javax.swing.JPasswordField();
        entradaConfirmarContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        etiquetaContraseñaActual.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaContraseñaActual.setText("Contraseña actual");
        etiquetaContraseñaActual.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaContraseñaActual);
        etiquetaContraseñaActual.setBounds(40, 104, 380, 20);

        btbCancelar.setBackground(new java.awt.Color(0, 0, 153));
        btbCancelar.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        btbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btbCancelar.setText("Cancelar");
        btbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btbCancelar);
        btbCancelar.setBounds(250, 320, 160, 29);

        btnAñadir.setBackground(new java.awt.Color(0, 0, 153));
        btnAñadir.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir);
        btnAñadir.setBounds(40, 320, 160, 29);

        etiquetaAñadir.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        etiquetaAñadir.setForeground(new java.awt.Color(0, 0, 102));
        etiquetaAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAñadir.setText("Cambiar Contraseña");
        etiquetaAñadir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiquetaAñadir.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent evt) {
                x = evt.getX();
                y = evt.getY();
            }
        });
        etiquetaAñadir.addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent evt) {
                Point point = MouseInfo.getPointerInfo().getLocation();
                setLocation(point.x - x, point.y - y);
            }
        });
        jPanel1.add(etiquetaAñadir);
        etiquetaAñadir.setBounds(0, -1, 440, 50);

        etiquetaContraseñaNueva.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaContraseñaNueva.setText("contraseña nueva");
        etiquetaContraseñaNueva.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaContraseñaNueva);
        etiquetaContraseñaNueva.setBounds(40, 174, 380, 20);

        etiquetaConfirmarContraseña.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaConfirmarContraseña.setText("confirmar contraseña");
        etiquetaConfirmarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaConfirmarContraseña);
        etiquetaConfirmarContraseña.setBounds(40, 254, 380, 20);

        entradaContraseñaActual.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaContraseñaActual.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaContraseñaActual.setOpaque(false);
        entradaContraseñaActual.addFocusListener(new EscucharBotones().focus(etiquetaContraseñaActual,0,0,153));
        entradaContraseñaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaContraseñaActualActionPerformed(evt);
            }
        });
        jPanel1.add(entradaContraseñaActual);
        entradaContraseñaActual.setBounds(40, 110, 360, 24);

        entradaContraseñaNueva.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaContraseñaNueva.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaContraseñaNueva.setOpaque(false);
        entradaContraseñaNueva.addFocusListener(new EscucharBotones().focus(etiquetaContraseñaNueva,0,0,153));
        entradaContraseñaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaContraseñaNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(entradaContraseñaNueva);
        entradaContraseñaNueva.setBounds(40, 180, 360, 24);

        entradaConfirmarContraseña.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaConfirmarContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaConfirmarContraseña.setOpaque(false);
        entradaConfirmarContraseña.addFocusListener(new EscucharBotones().focus(etiquetaConfirmarContraseña,0,0,153));
        entradaConfirmarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaConfirmarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(entradaConfirmarContraseña);
        entradaConfirmarContraseña.setBounds(40, 260, 360, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarActionPerformed
        // this.dispose();
        Fade.JDialogFadeOut(1f, 0f, 0.2f, 50, this, Fade.DISPOSE);
    }//GEN-LAST:event_btbCancelarActionPerformed
    private void cambiarContraseña() {
        if (String.valueOf(entradaContraseñaActual.getPassword()).equals("")
                || String.valueOf(entradaContraseñaActual.getPassword()).equals("")
                ||String.valueOf(entradaContraseñaActual.getPassword()).equals("")) {
            new sistema.alertas.Error(this, true, " TODOS LOS CAMPOS SON REQUERIDOS").setVisible(true);
        } else {
            UsuariosDTO user;
            ArrayList<UsuariosDTO> antiguo = Facade.ConsultarUsuario("Cedula", cedula);
            user = antiguo.get(0);
            if (!String.valueOf(entradaContraseñaActual.getPassword()).equals(user.getPassword())) {
                new sistema.alertas.Error(this, true, "LA CONTRASEÑA ACTUAL ES INCORRECTA").setVisible(true);
            } else {
                if (!String.valueOf(entradaContraseñaNueva.getPassword()).equals(
                    String.valueOf(entradaConfirmarContraseña.getPassword()))) {
                    new sistema.alertas.Error(this, true, "LAS CONTRASEÑAS NO COINCIDEN").setVisible(true);
                } else {
                    UsuariosDTO actualizado = new UsuariosDTO();
                    actualizado.setNombre(user.getNombre());
                    actualizado.setApellido(user.getApellido());
                    actualizado.setCedula(user.getCedula());
                    actualizado.setID(user.getID());
                    actualizado.setEmail(user.getEmail());
                    actualizado.setPassword(String.valueOf(entradaContraseñaNueva.getPassword()));
                    Facade.ActualizarUsuarios(user.getID(), actualizado);
                    new Hecho(this, true).setVisible(true);
                    Fade.JDialogFadeOut(1f, 0f, 0.2f, 50, this, Fade.DISPOSE);
                }
            }
        }
    }
    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        cambiarContraseña();
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void entradaContraseñaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaContraseñaActualActionPerformed
        entradaContraseñaNueva.requestFocus();
    }//GEN-LAST:event_entradaContraseñaActualActionPerformed

    private void entradaContraseñaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaContraseñaNuevaActionPerformed
        entradaConfirmarContraseña.requestFocus();
    }//GEN-LAST:event_entradaContraseñaNuevaActionPerformed

    private void entradaConfirmarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaConfirmarContraseñaActionPerformed
        cambiarContraseña();
    }//GEN-LAST:event_entradaConfirmarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CambiarPassword dialog = new CambiarPassword(new JDialog(), true, 26496153);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancelar;
    public javax.swing.JButton btnAñadir;
    private javax.swing.JPasswordField entradaConfirmarContraseña;
    private javax.swing.JPasswordField entradaContraseñaActual;
    private javax.swing.JPasswordField entradaContraseñaNueva;
    private javax.swing.JLabel etiquetaAñadir;
    public javax.swing.JLabel etiquetaConfirmarContraseña;
    public javax.swing.JLabel etiquetaContraseñaActual;
    public javax.swing.JLabel etiquetaContraseñaNueva;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
