/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.medico;

import Animacion.Fade;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.ArrayList;
import java.util.Collection;
import sistema.alertas.Hecho;
import sistema.alertas.Informacion;
import sistema.database.UsuariosDTO;
import sistema.util.Instancia;

/**
 *
 * @author Administrador
 */
public class EditarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form EditarUsuario
     */
    int x, y;
    int cedula;

    public EditarUsuario(java.awt.Frame parent, boolean modal, int Cedula) {
        super(parent, modal);
        setUndecorated(true);
        this.cedula = Cedula;
        initComponents();
        this.setLocationRelativeTo(parent);
        setOpacity(0f);
        Fade.JDialogFadeIn(0f, 1f, 0.2f, 50, this);
        llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("static-access")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        entradaNombre = new javax.swing.JTextField();
        btbCancelar = new javax.swing.JButton();
        btnCambiarContraseña = new javax.swing.JButton();
        etiquetaAñadir = new javax.swing.JLabel();
        etiquetaApellido = new javax.swing.JLabel();
        entradaApellido = new javax.swing.JTextField();
        etiquetaEmail = new javax.swing.JLabel();
        entradaEmail = new javax.swing.JTextField();
        etiquetaCedula = new javax.swing.JLabel();
        entradaCedula = new javax.swing.JTextField();
        etiquetaID = new javax.swing.JLabel();
        entradaID = new javax.swing.JTextField();
        btnAñadir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        etiquetaNombre.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaNombre.setText("Nombre");
        etiquetaNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaNombre);
        etiquetaNombre.setBounds(60, 104, 190, 20);

        entradaNombre.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaNombre.addFocusListener(new EscucharBotones().focus(etiquetaNombre,0,0,153));
        entradaNombre.addKeyListener(new EscucharBotones.AccionesTxt("texto"));
        entradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(entradaNombre);
        entradaNombre.setBounds(60, 110, 190, 24);

        btbCancelar.setBackground(new java.awt.Color(0, 0, 153));
        btbCancelar.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        btbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btbCancelar.setText("Cancelar");
        btbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btbCancelar);
        btbCancelar.setBounds(380, 420, 130, 29);

        btnCambiarContraseña.setBackground(new java.awt.Color(0, 0, 153));
        btnCambiarContraseña.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        btnCambiarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarContraseña.setText("Cambiar Contraseña");
        btnCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarContraseña);
        btnCambiarContraseña.setBounds(173, 420, 197, 29);

        etiquetaAñadir.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        etiquetaAñadir.setForeground(new java.awt.Color(0, 0, 102));
        etiquetaAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAñadir.setText("Editar Usuario");
        etiquetaAñadir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiquetaAñadir.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent evt) {
                x = evt.getX();
                y = evt.getY();
            }
        });
        etiquetaAñadir.addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent evt) {
                Point point = MouseInfo.getPointerInfo().getLocation();
                setLocation(point.x - x, point.y - y);
            }
        });
        jPanel1.add(etiquetaAñadir);
        etiquetaAñadir.setBounds(0, -1, 540, 50);

        etiquetaApellido.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaApellido.setText("Apellido");
        etiquetaApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaApellido);
        etiquetaApellido.setBounds(290, 104, 220, 20);

        entradaApellido.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaApellido.addFocusListener(new EscucharBotones().focus(etiquetaApellido,0,0,153));
        entradaApellido.addKeyListener(new EscucharBotones.AccionesTxt("texto"));
        entradaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(entradaApellido);
        entradaApellido.setBounds(290, 110, 190, 24);

        etiquetaEmail.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaEmail.setText("Email");
        etiquetaEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaEmail);
        etiquetaEmail.setBounds(100, 344, 220, 20);

        entradaEmail.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaEmail.addFocusListener(new EscucharBotones().focus(etiquetaEmail,0,0,153));
        entradaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaEmailActionPerformed(evt);
            }
        });
        jPanel1.add(entradaEmail);
        entradaEmail.setBounds(100, 350, 350, 24);

        etiquetaCedula.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaCedula.setText("Cedula");
        etiquetaCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaCedula);
        etiquetaCedula.setBounds(290, 224, 220, 20);

        entradaCedula.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaCedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaCedula.addFocusListener(new EscucharBotones().focus(etiquetaCedula,0,0,153));
        entradaCedula.addKeyListener(new EscucharBotones.AccionesTxt("numerico"));
        entradaCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(entradaCedula);
        entradaCedula.setBounds(290, 230, 190, 24);

        etiquetaID.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaID.setText("ID");
        etiquetaID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(etiquetaID);
        etiquetaID.setBounds(60, 224, 190, 20);

        entradaID.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        entradaID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        entradaID.addFocusListener(new EscucharBotones().focus(etiquetaID,0,0,153));
        entradaID.addKeyListener(new EscucharBotones.AccionesTxt("numerico"));
        entradaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaIDActionPerformed(evt);
            }
        });
        jPanel1.add(entradaID);
        entradaID.setBounds(60, 230, 190, 24);

        btnAñadir1.setBackground(new java.awt.Color(0, 0, 153));
        btnAñadir1.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        btnAñadir1.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir1.setText("Editar");
        btnAñadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir1);
        btnAñadir1.setBounds(30, 420, 130, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNombreActionPerformed
       entradaApellido.requestFocus();
    }//GEN-LAST:event_entradaNombreActionPerformed

    private void btbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarActionPerformed
        // this.dispose();
        Fade.JDialogFadeOut(1f, 0f, 0.2f, 50, this, Fade.DISPOSE);
    }//GEN-LAST:event_btbCancelarActionPerformed

    private void btnCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraseñaActionPerformed
        new CambiarPassword(this,true,cedula).setVisible(true);
    }//GEN-LAST:event_btnCambiarContraseñaActionPerformed

    private void entradaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaApellidoActionPerformed
        entradaID.requestFocus();
    }//GEN-LAST:event_entradaApellidoActionPerformed

    private void entradaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaEmailActionPerformed
         añadirUser();
    }//GEN-LAST:event_entradaEmailActionPerformed

    private void entradaCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCedulaActionPerformed
        entradaEmail.requestFocus();
    }//GEN-LAST:event_entradaCedulaActionPerformed

    private void entradaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaIDActionPerformed
        entradaCedula.requestFocus();
    }//GEN-LAST:event_entradaIDActionPerformed

    private void llenarCampos() {
        Collection<UsuariosDTO> coll;
        coll = Facade.ConsultarUsuario("Cedula", cedula);
        for (UsuariosDTO dto : coll) {
            entradaNombre.setText(dto.getNombre());
            entradaApellido.setText(dto.getApellido());
            entradaCedula.setText("" + dto.getCedula());
            entradaID.setText("" + dto.getID());
            entradaEmail.setText(dto.getEmail());
            new EscucharBotones.focus().subir(etiquetaApellido,
                    entradaApellido, 0, 0, 153);
            new EscucharBotones.focus().subir(etiquetaCedula,
                    entradaCedula, 0, 0, 153);
            new EscucharBotones.focus().subir(etiquetaEmail,
                    entradaEmail, 0, 0, 153);
            new EscucharBotones.focus().subir(etiquetaID,
                    entradaID, 0, 0, 153);
            entradaNombre.requestFocus();
        }
    }
    private void añadirUser(){
        if (entradaNombre.getText().equals("") || entradaApellido.getText().equals("")
                || entradaCedula.getText().equals("") || entradaID.getText().equals("")
                || entradaEmail.getText().equals("")) {
            new sistema.alertas.Error(this, true, " TODOS LOS CAMPOS SON REQUERIDOS").setVisible(true);
        } else {
            UsuariosDTO user;
            ArrayList<UsuariosDTO> antiguo = Facade.ConsultarUsuario("Cedula", cedula);
            user=antiguo.get(0);
            Collection<UsuariosDTO> coll = Facade.ConsultarUsuario("ID", Integer.parseInt(entradaID.getText()));
            if (!coll.isEmpty() && Integer.parseInt(entradaID.getText())!=user.getID() ) {
                new sistema.alertas.Error(this, true, "YA EXISTE UN USUARIO CON ESE ID").setVisible(true);
            } else {
                coll = Facade.ConsultarUsuario("Cedula", Integer.parseInt(entradaCedula.getText()));
                if (!coll.isEmpty() && Integer.parseInt(entradaCedula.getText())!=user.getCedula()) {
                    new sistema.alertas.Error(this, true, "YA EXISTE UN USUARIO CON ESE NUMERO DE CEDULA").setVisible(true);
                } else {
                    if(entradaNombre.getText().toUpperCase().equals(user.getNombre())
                            &&entradaApellido.getText().toUpperCase().equals(user.getApellido())
                            &&entradaEmail.getText().equals(user.getEmail())
                            &&Integer.parseInt(entradaCedula.getText())==user.getCedula()
                            &&Integer.parseInt(entradaID.getText())==user.getID()){
                          new Informacion(this, true, "\n NO HA MODIFICADO SUS DATOS").setVisible(true);
                    }else{
                        UsuariosDTO actualizado=new UsuariosDTO();
                        actualizado.setNombre(entradaNombre.getText().toUpperCase());
                        actualizado.setApellido(entradaApellido.getText().toUpperCase());
                        actualizado.setCedula(Integer.parseInt(entradaCedula.getText()));
                        actualizado.setID(Integer.parseInt(entradaID.getText()));
                        actualizado.setEmail(entradaEmail.getText());
                        actualizado.setPassword(user.getPassword());
                        Facade.ActualizarUsuarios(user.getID(), actualizado);
                        new Hecho(this,true).setVisible(true);
                        principal obj = (principal) Instancia.getInstancia("medico.principal");
                        obj.cedula.setText(entradaCedula.getText());
                        obj.datosUser();
                    }
                    Fade.JDialogFadeOut(1f, 0f, 0.2f, 50, this, Fade.DISPOSE);
                }
            }
        }
    }
    private void btnAñadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadir1ActionPerformed
        añadirUser();
    }//GEN-LAST:event_btnAñadir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarUsuario dialog = new EditarUsuario(new javax.swing.JFrame(), true, 26496153);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancelar;
    public javax.swing.JButton btnAñadir1;
    public javax.swing.JButton btnCambiarContraseña;
    public javax.swing.JTextField entradaApellido;
    public javax.swing.JTextField entradaCedula;
    public javax.swing.JTextField entradaEmail;
    public javax.swing.JTextField entradaID;
    public javax.swing.JTextField entradaNombre;
    public javax.swing.JLabel etiquetaApellido;
    private javax.swing.JLabel etiquetaAñadir;
    public javax.swing.JLabel etiquetaCedula;
    public javax.swing.JLabel etiquetaEmail;
    public javax.swing.JLabel etiquetaID;
    public javax.swing.JLabel etiquetaNombre;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
