/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.medico;

import Animacion.Fade;
import diu.swe.habib.JPanelSlider.*;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.net.URI;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import sistema.alertas.Hecho;
import sistema.database.BaseDeDatos;
import sistema.database.UsuariosDTO;
import sistema.util.Instancia;

/**
 *
 * @author Administrador
 */
public class Login extends JFrame {

    /**
     * Creates new form LoginPrin
     */
    JFrame parent;

    public Login() {
        setLookAndFeel("Metal");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setUndecorated(true);
        initComponents();
        parent = this;
        this.setLocationRelativeTo(null);
        Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, this);
        entradaCedulap.requestFocus();
        BaseDeDatos.crearTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanelSlider1 = new JPanelSlider();
        panelInicioSesion = new JPanel();
        etiquetaIniciarSesion = new JLabel();
        estradaContraseña = new JPasswordField();
        entradaCedulap = new JTextField();
        btnEntrar = new JButton();
        etiquetaRecuperacionContraseña = new JLabel();
        iconoGoogle = new JLabel();
        iconoFacebook = new JLabel();
        etiquetaContraseña = new JLabel();
        etiquetaRegistrarse = new JLabel();
        etiquetaCedula = new JLabel();
        btnMinimizar = new JButton();
        btnCerrar = new JButton();
        fondoPanelInicioSesion = new JLabel();
        panelRegistrarse = new JPanel();
        etiquetaRegistrarse1 = new JLabel();
        entradaContraseña = new JPasswordField();
        entradaCedula = new JTextField();
        btnRegistrar = new JButton();
        iconoGoogle1 = new JLabel();
        iconoFacebook1 = new JLabel();
        etiquetaContraseña1 = new JLabel();
        etiquetaEntrar = new JLabel();
        etiquetaCedula1 = new JLabel();
        btnMinimizar1 = new JButton();
        btnCerrar1 = new JButton();
        entradaConfirmacionContraseña = new JPasswordField();
        etiquetaConfirmacionContraseña = new JLabel();
        fondoPanelRegistrarse = new JLabel();
        jPanelSlider2 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jPanel3 = new JPanel();
        jPanel4 = new JPanel();
        etiquetaNombre = new JLabel();
        entradaNombre = new javax.swing.JTextField();
        entradaApellido = new javax.swing.JTextField();
        etiquetaApellido = new javax.swing.JLabel();
        entradaEmail = new javax.swing.JTextField();
        etiquetaEmail = new javax.swing.JLabel();
        etiquetaID = new javax.swing.JLabel();
        entradaID = new javax.swing.JTextField();
        iconoConectar = new javax.swing.JLabel();
        iconoConectar1 = new javax.swing.JLabel();
        btnSiguiente = new JButton();
        btnAtras = new JButton();

        jPanelSlider1.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));

        panelInicioSesion.setLayout(null);

        etiquetaIniciarSesion.setFont(new Font("Mangal", 0, 28)); // NOI18N
        etiquetaIniciarSesion.setForeground(new Color(255, 255, 255));
        etiquetaIniciarSesion.setText("Iniciar Sesión");
        panelInicioSesion.add(etiquetaIniciarSesion);
        etiquetaIniciarSesion.setBounds(20, 30, 190, 40);

        etiquetaCedula = new JLabel();
        etiquetaCedula.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaCedula.setForeground(new Color(255, 255, 255));
        etiquetaCedula.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        etiquetaCedula.setText("Cedula");

        panelInicioSesion.add(etiquetaCedula);
        etiquetaCedula.setBounds(210, 164, 60, 30);

        entradaCedulap.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaCedulap.setForeground(new Color(204, 204, 204));
        entradaCedulap.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(180, 180, 180)));
        entradaCedulap.setOpaque(false);
        entradaCedulap.setCaretColor(new Color(204, 204, 204));
        entradaCedulap.addActionListener((ActionEvent e) -> {
            estradaContraseña.requestFocus();
        });
        entradaCedulap.addFocusListener(EscucharBotones.focus(etiquetaCedula, 255, 255, 255));
        entradaCedulap.addKeyListener(new EscucharBotones.AccionesTxt("numerico"));

        panelInicioSesion.add(entradaCedulap);
        entradaCedulap.setBounds(210, 170, 290, 30);

        etiquetaContraseña.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaContraseña.setForeground(new Color(255, 255, 255));
        etiquetaContraseña.setText("Contraseña");
        etiquetaContraseña.setCursor(new Cursor(Cursor.TEXT_CURSOR));

        panelInicioSesion.add(etiquetaContraseña);
        etiquetaContraseña.setBounds(210, 264, 120, 30);

        estradaContraseña.setForeground(new Color(204, 204, 204));
        estradaContraseña.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(180, 180, 180)));
        estradaContraseña.setOpaque(false);
        estradaContraseña.setCaretColor(new Color(204, 204, 204));
        estradaContraseña.addActionListener((ActionEvent e) -> {
            iniciarSesion();
        });
        estradaContraseña.addFocusListener(EscucharBotones.focus(etiquetaContraseña, 255, 255, 255));

        panelInicioSesion.add(estradaContraseña);
        estradaContraseña.setBounds(210, 270, 290, 30);

        btnEntrar.setBackground(new Color(0, 0, 0));
        btnEntrar.setForeground(new Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorder(null);
        btnEntrar.setFocusPainted(false);
        btnEntrar.setBorderPainted(false);
        btnEntrar.addActionListener((ActionEvent e) -> {
            iniciarSesion();
        });
        panelInicioSesion.add(btnEntrar);
        btnEntrar.setBounds(250, 380, 230, 20);

        etiquetaRecuperacionContraseña.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        etiquetaRecuperacionContraseña.setForeground(new Color(255, 255, 255));
        etiquetaRecuperacionContraseña.setText("¿Ha olvidado Contraseña?");
        panelInicioSesion.add(etiquetaRecuperacionContraseña);
        etiquetaRecuperacionContraseña.setBounds(290, 430, 210, 20);

        iconoGoogle.setIcon(new ImageIcon(getClass().getResource("/img/icons8-google-plus-circled-filled-64.png"))); // NOI18N
        iconoGoogle.setCursor(new Cursor(Cursor.HAND_CURSOR));
        panelInicioSesion.add(iconoGoogle);
        iconoGoogle.setBounds(20, 230, 70, 50);
        iconoGoogle.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                try {
                    Desktop.getDesktop().browse(URI.create("https://www.google.com/"));
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        iconoConectar.setIcon(new ImageIcon(getClass().getResource("/img/icono conectar.png"))); // NOI18N
        iconoConectar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        panelInicioSesion.add(iconoConectar);
        iconoConectar.setBounds(20, 310, 70, 50);
        iconoConectar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                new ConectarBD(parent, true).setVisible(true);
            }
        });

        iconoFacebook.setIcon(new ImageIcon(getClass().getResource("/img/icons8-facebook-rodeado-de-círculo-filled-64.png"))); // NOI18N
        iconoFacebook.setCursor(new Cursor(Cursor.HAND_CURSOR));
        panelInicioSesion.add(iconoFacebook);
        iconoFacebook.setBounds(20, 150, 70, 50);
        iconoFacebook.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                try {
                    Desktop.getDesktop().browse(URI.create("https://www.facebook.com/"));
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        btnCerrar.setIcon(new ImageIcon(getClass().getResource("/img/icono cerrar Login.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setRolloverIcon(new ImageIcon(getClass().getResource("/img/icono cerrar Login rollover.png"))); // NOI18N
        btnCerrar.setFocusPainted(false);
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.addActionListener((ActionEvent e) -> {
            Fade.JFrameFadeOut(1f, 0f, 0.2f, 50, this, Fade.EXIT);
        });

        panelInicioSesion.add(btnCerrar);
        btnCerrar.setBounds(764, 4, 30, 20);

        btnMinimizar.setIcon(new ImageIcon(getClass().getResource("/img/icono minimizar login.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setRolloverIcon(new ImageIcon(getClass().getResource("/img/icono minimizar login rollover.png"))); // NOI18N
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener((ActionEvent e) -> {
            setExtendedState(ICONIFIED);
        });

        panelInicioSesion.add(btnMinimizar);
        btnMinimizar.setBounds(730, 4, 30, 20);

        etiquetaRegistrarse.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaRegistrarse.setForeground(new Color(255, 255, 255));
        etiquetaRegistrarse.setText("REGISTRARSE");
        etiquetaRegistrarse.setCursor(new Cursor(Cursor.HAND_CURSOR));
        etiquetaRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panelInicioSesion.add(etiquetaRegistrarse);
        etiquetaRegistrarse.setBounds(650, 230, 110, 30);

        fondoPanelInicioSesion.setIcon(new ImageIcon(getClass().getResource("/img/PANEL1.jpg"))); // NOI18N
        panelInicioSesion.add(fondoPanelInicioSesion);
        fondoPanelInicioSesion.setBounds(0, 0, 800, 502);

        jPanelSlider1.add(panelInicioSesion, "card2");
        panelRegistrarse.setLayout(null);

        jPanelSlider2.setBorder(null);
        jPanelSlider2.setOpaque(false);
        panelRegistrarse.add(jPanelSlider2);
        jPanelSlider2.setBounds(290, 110, 370, 330);

        etiquetaRegistrarse1.setFont(new Font("Mangal", 0, 28)); // NOI18N
        etiquetaRegistrarse1.setForeground(new Color(255, 255, 255));
        etiquetaRegistrarse1.setText("Registrarse");
        panelRegistrarse.add(etiquetaRegistrarse1);
        etiquetaRegistrarse1.setBounds(550, 30, 190, 40);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        etiquetaNombre.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaNombre.setForeground(new Color(255, 255, 255));
        etiquetaNombre.setText("Nombre");
        etiquetaNombre.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jPanel3.add(etiquetaNombre);
        etiquetaNombre.setBounds(0, 10, 100, 30);

        entradaNombre.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaNombre.setForeground(new Color(204, 204, 204));
        entradaNombre.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        entradaNombre.setOpaque(false);
        entradaNombre.setCaretColor(new Color(204, 204, 204));
        jPanel3.add(entradaNombre);
        entradaNombre.addActionListener((ActionEvent e) -> {
            entradaApellido.requestFocus();
        });
        entradaNombre.addFocusListener(EscucharBotones.focus(etiquetaNombre, 255, 255, 255));
        entradaNombre.addKeyListener(new EscucharBotones.AccionesTxt("texto"));
        entradaNombre.setBounds(0, 16, 290, 30);

        etiquetaApellido.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaApellido.setForeground(new Color(255, 255, 255));
        etiquetaApellido.setText("Apelido");
        etiquetaApellido.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jPanel3.add(etiquetaApellido);
        etiquetaApellido.setBounds(0, 84, 100, 30);

        entradaApellido.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaApellido.setForeground(new Color(204, 204, 204));
        entradaApellido.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        entradaApellido.setOpaque(false);
        entradaApellido.setCaretColor(new Color(204, 204, 204));
        jPanel3.add(entradaApellido);
        entradaApellido.addActionListener((ActionEvent e) -> {
            entradaCedula.requestFocus();
        });
        entradaApellido.addKeyListener(new EscucharBotones.AccionesTxt("texto"));
        entradaApellido.addFocusListener(EscucharBotones.focus(etiquetaApellido, 255, 255, 255));
        entradaApellido.setBounds(0, 90, 290, 30);

        etiquetaCedula1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaCedula1.setForeground(new Color(255, 255, 255));
        etiquetaCedula1.setText("Cedula");
        etiquetaCedula1.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jPanel3.add(etiquetaCedula1);
        etiquetaCedula1.setBounds(0, 158, 60, 30);

        entradaCedula.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaCedula.setForeground(new Color(204, 204, 204));
        entradaCedula.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(180, 180, 180)));
        entradaCedula.setOpaque(false);
        entradaCedula.setCaretColor(new Color(204, 204, 204));
        entradaCedula.addActionListener((ActionEvent e) -> {
            entradaEmail.requestFocus();
        });
        entradaCedula.addKeyListener(new EscucharBotones.AccionesTxt("numerico"));
        entradaCedula.addFocusListener(EscucharBotones.focus(etiquetaCedula1, 255, 255, 255));
        jPanel3.add(entradaCedula);
        entradaCedula.setBounds(0, 164, 290, 30);

        etiquetaEmail.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaEmail.setForeground(new Color(255, 255, 255));
        etiquetaEmail.setText("Email");
        etiquetaEmail.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jPanel3.add(etiquetaEmail);
        etiquetaEmail.setBounds(0, 232, 60, 30);

        entradaEmail.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaEmail.setForeground(new Color(204, 204, 204));
        entradaEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(180, 180, 180)));
        entradaEmail.setOpaque(false);
        entradaEmail.setCaretColor(new Color(204, 204, 204));
        entradaEmail.addActionListener((ActionEvent e) -> {
            if (entradaNombre.getText().equals("") || entradaApellido.getText().equals("")
                    || entradaCedula.getText().equals("") || entradaEmail.getText().equals("")) {
                new sistema.alertas.Error(this, true, "\n TODOS LOS CAMPOS SON REQUERIDOS").setVisible(true);
            } else {
                jPanelSlider2.nextPanel(5, jPanel4, JPanelSlider.left);
                entradaID.requestFocus();
            }
        });
        entradaEmail.addFocusListener(EscucharBotones.focus(etiquetaEmail, 255, 255, 255));
        jPanel3.add(entradaEmail);
        entradaEmail.setBounds(0, 238, 290, 30);

        btnSiguiente.setBackground(new Color(0, 0, 0));
        btnSiguiente.setForeground(new Color(255, 255, 255));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(null);
        btnSiguiente.setFocusPainted(false);
        btnSiguiente.setBorderPainted(false);
        jPanel3.add(btnSiguiente);
        btnSiguiente.setBounds(40, 308, 230, 20);
        btnSiguiente.setFocusPainted(false);
        btnSiguiente.addActionListener((ActionEvent e) -> {
            if (entradaNombre.getText().equals("") || entradaApellido.getText().equals("")
                    || entradaCedula.getText().equals("") || entradaEmail.getText().equals("")) {
                new sistema.alertas.Error(this, true, "\n TODOS LOS CAMPOS SON REQUERIDOS").setVisible(true);
            } else {
                jPanelSlider2.nextPanel(5, jPanel4, JPanelSlider.left);
                entradaID.requestFocus();
            }
        });

        jPanelSlider2.add(jPanel3, "card2");

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        etiquetaID.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaID.setForeground(new Color(255, 255, 255));
        etiquetaID.setText("ID");
        etiquetaID.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jPanel4.add(etiquetaID);
        etiquetaID.setBounds(0, 10, 120, 30);

        entradaID.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaID.setForeground(new Color(204, 204, 204));
        entradaID.setCaretColor(new Color(204, 204, 204));
        entradaID.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(180, 180, 180)));
        entradaID.setOpaque(false);
        entradaID.addActionListener((ActionEvent e) -> {
            entradaContraseña.requestFocus();
        });
        entradaID.addKeyListener(new EscucharBotones.AccionesTxt("numerico"));
        entradaID.addFocusListener(EscucharBotones.focus(etiquetaID, 255, 255, 255));
        jPanel4.add(entradaID);
        entradaID.setBounds(0, 16, 290, 30);

        etiquetaContraseña1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaContraseña1.setForeground(new Color(255, 255, 255));
        etiquetaContraseña1.setText("Contraseña");
        etiquetaContraseña1.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jPanel4.add(etiquetaContraseña1);
        etiquetaContraseña1.setBounds(0, 84, 120, 30);

        entradaContraseña.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaContraseña.setForeground(new Color(204, 204, 204));
        entradaContraseña.setCaretColor(new Color(204, 204, 204));
        entradaContraseña.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(180, 180, 180)));
        entradaContraseña.setOpaque(false);
        entradaContraseña.addActionListener((ActionEvent e) -> {
            entradaConfirmacionContraseña.requestFocus();
        });
        entradaContraseña.addFocusListener(EscucharBotones.focus(etiquetaContraseña1, 255, 255, 255));
        jPanel4.add(entradaContraseña);
        entradaContraseña.setBounds(0, 90, 290, 30);

        etiquetaConfirmacionContraseña.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaConfirmacionContraseña.setForeground(new Color(255, 255, 255));
        etiquetaConfirmacionContraseña.setText("Confirmar contraseña");
        etiquetaConfirmacionContraseña.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jPanel4.add(etiquetaConfirmacionContraseña);
        etiquetaConfirmacionContraseña.setBounds(0, 158, 200, 30);

        entradaConfirmacionContraseña.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        entradaConfirmacionContraseña.setForeground(new java.awt.Color(204, 204, 204));
        entradaConfirmacionContraseña.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(180, 180, 180)));
        entradaConfirmacionContraseña.setOpaque(false);
        entradaConfirmacionContraseña.setCaretColor(new Color(204, 204, 204));
        entradaConfirmacionContraseña.addActionListener((ActionEvent e) -> {
            registrar();
        });
        entradaConfirmacionContraseña.addFocusListener(EscucharBotones.focus(etiquetaConfirmacionContraseña, 255, 255, 255));
        jPanel4.add(entradaConfirmacionContraseña);
        entradaConfirmacionContraseña.setBounds(0, 164, 290, 30);

        btnRegistrar.setBackground(new Color(0, 0, 0));
        btnRegistrar.setForeground(new Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener((ActionEvent e) -> {
            registrar();
        });
        jPanel4.add(btnRegistrar);
        btnRegistrar.setBounds(190, 308, 170, 20);
        btnRegistrar.setFocusPainted(false);

        btnAtras.setBackground(new Color(0, 0, 0));
        btnAtras.setForeground(new Color(255, 255, 255));
        btnAtras.setText("REGRESAR");
        btnAtras.setBorder(null);
        btnAtras.setFocusPainted(false);
        btnAtras.setBorderPainted(false);
        jPanel4.add(btnAtras);
        btnAtras.setBounds(0, 308, 170, 20);
        btnAtras.setFocusPainted(false);
        btnAtras.addActionListener((ActionEvent e) -> {
            jPanelSlider2.nextPanel(5, jPanel3, JPanelSlider.right);
        });

        jPanelSlider2.add(jPanel4, "card3");

        iconoGoogle1.setIcon(new ImageIcon(getClass().getResource("/img/icons8-google-plus-circled-filled-64.png"))); // NOI18N
        iconoGoogle1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        panelRegistrarse.add(iconoGoogle1);
        iconoGoogle1.setBounds(700, 230, 70, 50);
        iconoGoogle1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                try {
                    Desktop.getDesktop().browse(URI.create("https://www.google.com/"));
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        iconoConectar1.setIcon(new ImageIcon(getClass().getResource("/img/icono conectar.png"))); // NOI18N
        iconoConectar1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        panelRegistrarse.add(iconoConectar1);
        iconoConectar1.setBounds(700, 310, 70, 50);
        iconoConectar1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                new ConectarBD(parent, true).setVisible(true);
            }
        });
        iconoFacebook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-facebook-rodeado-de-círculo-filled-64.png"))); // NOI18N
        iconoFacebook1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        panelRegistrarse.add(iconoFacebook1);
        iconoFacebook1.setBounds(700, 150, 70, 50);
        iconoFacebook1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                try {
                    Desktop.getDesktop().browse(URI.create("https://www.facebook.com/"));
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        etiquetaEntrar.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        etiquetaEntrar.setForeground(new Color(255, 255, 255));
        etiquetaEntrar.setText("ENTRAR");
        etiquetaEntrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        etiquetaEntrar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        panelRegistrarse.add(etiquetaEntrar);
        etiquetaEntrar.setBounds(70, 230, 90, 30);

        btnCerrar1.setIcon(new ImageIcon(getClass().getResource("/img/icono cerrar Login.png"))); // NOI18N
        btnCerrar1.setBorder(null);
        btnCerrar1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar1.setBorderPainted(false);
        btnCerrar1.setContentAreaFilled(false);
        btnCerrar1.setFocusPainted(false);
        btnCerrar1.setRolloverIcon(new ImageIcon(getClass().getResource("/img/icono cerrar Login rollover.png"))); // NOI18N
        btnCerrar1.addActionListener((ActionEvent e) -> {
            Fade.JFrameFadeOut(1f, 0f, 0.2f, 50, this, Fade.EXIT);
        });
        panelRegistrarse.add(btnCerrar1);
        btnCerrar1.setBounds(764, 4, 30, 20);

        btnMinimizar1.setIcon(new ImageIcon(getClass().getResource("/img/icono minimizar login.png"))); // NOI18N
        btnMinimizar1.setBorder(null);
        btnMinimizar1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnMinimizar1.setBorderPainted(false);
        btnMinimizar1.setFocusPainted(false);
        btnMinimizar1.setContentAreaFilled(false);
        btnMinimizar1.setRolloverIcon(new ImageIcon(getClass().getResource("/img/icono minimizar login rollover.png"))); // NOI18N
        btnMinimizar1.addActionListener((ActionEvent e) -> {
            setExtendedState(ICONIFIED);
        });
        panelRegistrarse.add(btnMinimizar1);
        btnMinimizar1.setBounds(730, 4, 30, 20);

        fondoPanelRegistrarse.setIcon(new ImageIcon(getClass().getResource("/img/PANEL2.jpg"))); // NOI18N
        fondoPanelRegistrarse.setToolTipText("");
        panelRegistrarse.add(fondoPanelRegistrarse);
        fondoPanelRegistrarse.setBounds(0, 0, 800, 502);

        jPanelSlider1.add(panelRegistrarse, "card2");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelSlider1, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelSlider1, GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void iniciarSesion() {
        boolean aux = false;
        setLookAndFeel("Nimbus");
        if (entradaCedulap.getText().equals("") && estradaContraseña.getPassword().toString().equals("")) {
            new sistema.alertas.Error(this, true, " TODOS LOS CAMPOS SON REQUERIDOS").setVisible(true);
            entradaCedulap.requestFocus();
        } else if (entradaCedulap.getText().equals("")) {
            new sistema.alertas.Error(this, true, "LA CEDULA/ID ES REQUERIDA").setVisible(true);
            entradaCedulap.requestFocus();
        } else if (String.valueOf(estradaContraseña.getPassword()).equals("")) {
            new sistema.alertas.Error(this, true, "LA CONTRASEÑA ES REQUERIDA").setVisible(true);
            estradaContraseña.requestFocus();
        } else {
            Collection<UsuariosDTO> user = Facade.ConsultarUsuario("ID", Integer.parseInt(entradaCedulap.getText()));
            if (user.isEmpty()) {
                user = Facade.ConsultarUsuario("Cedula", Integer.parseInt(entradaCedulap.getText()));
            }
            for (UsuariosDTO dto : user) {
                System.out.println(dto);
                if ((dto.getID() == Integer.parseInt(entradaCedulap.getText())
                        && dto.getPassword().equals(String.valueOf(estradaContraseña.getPassword())))
                        || (dto.getCedula() == Integer.parseInt(entradaCedulap.getText())
                        && dto.getPassword().equals(String.valueOf(estradaContraseña.getPassword()).toString()))) {
                    aux = true;
                    principal obj =  ((principal)Instancia.getInstancia("medico.principal"));
                    obj.cedula.setText(entradaCedulap.getText());
                    Fade.JFrameFadeIn(0f,1f,0.2f,50,obj);
                    obj.setVisible(true);
                    Fade.JFrameFadeOut(1f, 0f, 0.2f, 50, this,Fade.DISPOSE);
                }
            }
            if (!aux) {
               
                new sistema.alertas.Error(this, true, " USUARIO O CONTRASEÑA INVALIDO").setVisible(true);
                entradaCedulap.setText("");
                estradaContraseña.setText("");
                entradaCedulap.requestFocus();
                //this.dispose();
            }
        }
    }

    private void registrar() {
        System.out.println(entradaConfirmacionContraseña.getPassword());
        System.out.println(entradaContraseña.getPassword());
        if (entradaID.getText().equals("") || String.valueOf(entradaContraseña.getPassword()).equals("")
                || String.valueOf(entradaConfirmacionContraseña.getPassword()).equals("")) {
            new sistema.alertas.Error(this, true, " TODOS LOS CAMPOS SON REQUERIDOS").setVisible(true);
        } else if (!String.valueOf(entradaContraseña.getPassword()).equals(String.valueOf(entradaConfirmacionContraseña.getPassword()))) {
            new sistema.alertas.Error(this, true, "LAS CONTRASEÑAS NO COINCIDEN").setVisible(true);
        } else {
            int result = 0;
            Collection<UsuariosDTO> user = Facade.ConsultarUsuario("ID", Integer.parseInt(entradaID.getText()));
            for (UsuariosDTO dto : user) {
                result = dto.getTotalFilasAfectadas();
            }
            if (result != 0) {
                new sistema.alertas.Error(this, true, "YA EXISTE UN USUARIO CON ESE ID").setVisible(true);
            } else {
                user = Facade.ConsultarUsuario("Cedula", Integer.parseInt(entradaCedula.getText()));
                for (UsuariosDTO dto : user) {
                    result = dto.getTotalFilasAfectadas();
                }
                if (result != 0) {
                    new sistema.alertas.Error(this, true, "\n YA EXISTE UN USUARIO CON ESE NUMERO DE CEDULA").setVisible(true);
                } else {
                    UsuariosDTO Usuario = new UsuariosDTO();
                    Usuario.setNombre(entradaNombre.getText().toUpperCase());
                    Usuario.setApellido(entradaApellido.getText().toUpperCase());
                    Usuario.setCedula(Integer.parseInt(entradaCedula.getText()));
                    Usuario.setID(Integer.parseInt(entradaID.getText()));
                    Usuario.setEmail(entradaEmail.getText().toUpperCase());
                    Usuario.setPassword(String.valueOf(entradaConfirmacionContraseña.getPassword()));
                    //Usuario.setTipoCuenta();
                    Facade.AñadirUsuarios(Usuario);
                    new Hecho(this, true).setVisible(true);
                    jPanelSlider1.nextPanel(5, panelInicioSesion, JPanelSlider.right);
                    jPanelSlider2.nextPanel(5, jPanel3, JPanelSlider.right);
                    entradaNombre.setText("");
                    entradaApellido.setText("");
                    entradaCedula.setText("");
                    entradaEmail.setText("");
                    entradaID.setText("");
                    entradaContraseña.setText("");
                    entradaConfirmacionContraseña.setText("");
                    entradaCedulap.requestFocus();
                }
            }
        }
    }

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {
        jPanelSlider1.nextPanel(5, panelRegistrarse, JPanelSlider.left);
        entradaNombre.requestFocus();
    }

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {
        jPanelSlider1.nextPanel(5, panelInicioSesion, JPanelSlider.right);
        entradaCedulap.requestFocus();
    }
    private void setLookAndFeel(String tema){
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (!tema.equals(info.getName())) {
                } else {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (!"Metal".equals(info.getName())) {
                } else {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
            new Login().setVisible(true);
           // Facade.actividadesPorDefecto();
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPasswordField estradaContraseña;
    private javax.swing.JPasswordField entradaContraseña;
    private javax.swing.JPasswordField entradaConfirmacionContraseña;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel fondoPanelInicioSesion;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel etiquetaRegistrarse;
    private javax.swing.JLabel iconoGoogle1;
    private javax.swing.JLabel iconoConectar;
    private javax.swing.JLabel iconoConectar1;
    private javax.swing.JLabel iconoFacebook1;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaEntrar;
    private javax.swing.JLabel etiquetaCedula;
    private javax.swing.JButton btnMinimizar1;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JLabel etiquetaIniciarSesion;
    private javax.swing.JLabel fondoPanelRegistrarse;
    private javax.swing.JLabel etiquetaConfirmacionContraseña;
    private javax.swing.JLabel etiquetaRecuperacionContraseña;
    private javax.swing.JLabel iconoGoogle;
    private javax.swing.JLabel iconoFacebook;
    private javax.swing.JLabel etiquetaContraseña1;
    private javax.swing.JLabel etiquetaRegistrarse1;
    private javax.swing.JLabel etiquetaCedula1;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JPanel panelRegistrarse;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JTextField entradaCedulap;
    private javax.swing.JTextField entradaCedula;
    private javax.swing.JLabel etiquetaApellido;
    private javax.swing.JLabel etiquetaEmail;
    private javax.swing.JTextField entradaApellido;
    private javax.swing.JTextField entradaEmail;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JTextField entradaID;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnAtras;
    // End of variables declaration                   
}
