/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.alertas;

//import sistema.necesario.RSAWTUtilities;
import Animacion.Fade;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Administrador
 */
public class Informacion extends javax.swing.JDialog {

    /**
     * Creates new form Informacion
     */
    public Informacion(JFrame parent, boolean modal, String text) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        msj.setText(text);
        setOpacity(0f);
        //RSAWTUtilities.setOpaque(this, false);
        this.setLocationRelativeTo(parent);
        this.setLocationRelativeTo(this);
        Fade.JDialogFadeIn(0, 1, 0.2f, 50, this);
    }
    public Informacion(JDialog parent, boolean modal, String text) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        msj.setText(text);
        setOpacity(0f);
        //RSAWTUtilities.setOpaque(this, false);
        this.setLocationRelativeTo(parent);
        this.setLocationRelativeTo(this);
        Fade.JDialogFadeIn(0, 1, 0.2f, 50, this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boton_Entrar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        msj = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono info.png"))); // NOI18N
        jLabel2.setText("  ¡ Informacion !");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(2, 0, 490, 70);

        boton_Entrar2.setBackground(new java.awt.Color(0, 0, 153));
        boton_Entrar2.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        boton_Entrar2.setForeground(new java.awt.Color(255, 255, 255));
        boton_Entrar2.setText("Entendido");
        boton_Entrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Entrar2ActionPerformed(evt);
            }
        });
        boton_Entrar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_Entrar2KeyPressed(evt);
            }
        });
        jPanel1.add(boton_Entrar2);
        boton_Entrar2.setBounds(170, 180, 160, 29);

        jScrollPane2.setBorder(null);

        StyledDocument doc = msj.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        msj.setEditable(false);
        msj.setBorder(null);
        msj.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        msj.setFocusable(false);
        jScrollPane2.setViewportView(msj);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 90, 430, 72);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Entrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Entrar2ActionPerformed
        Fade.JDialogFadeOut(1, 0, 0.1f, 50, this, Fade.DISPOSE);
    }//GEN-LAST:event_boton_Entrar2ActionPerformed

    private void boton_Entrar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_Entrar2KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            Fade.JDialogFadeOut(1, 0, 0.1f, 50, this, Fade.DISPOSE);
        } 
    }//GEN-LAST:event_boton_Entrar2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Informacion dialog = new Informacion(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Entrar2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane msj;
    // End of variables declaration//GEN-END:variables
}
